# -*- coding: utf-8 -*-
"""dialect_alignment (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A9IPcDpmxmpjK1PO4aR73MEvtQ4-cbSy

## 1. установка библиотек и импорты
"""

# Commented out IPython magic to ensure Python compatibility.
# %env CUDA_VISIBLE_DEVICES=2

!python --version

!pip install lingtrain_aligner==1.0.2 razdel python-Levenshtein pandas sentence-transformers

# импортируем все библиотеки
import re
import os
import pandas as pd
import numpy as np
from typing import List, Tuple, Dict
from dataclasses import dataclass
from Levenshtein import distance as lev_distance
import warnings
warnings.filterwarnings('ignore')

# из lingtrain берем все для выравнивания
from lingtrain_aligner import preprocessor, splitter, aligner, resolver, reader, helper, vis_helper, metrics
from sentence_transformers import SentenceTransformer
from scipy.spatial.distance import cosine
from razdel import sentenize

"""## 2. структуры данных и функции парсинга"""

@dataclass
class WhisperSegment:
    """сегмент из whisper srt - один блок с таймкодами и текстом"""
    start_time: float  # время начала в секундах
    end_time: float    # время конца в секундах
    speaker: str       # спикер (SPEAKER_00, SPEAKER_01 и тд)
    text: str          # сам текст
    is_dialect: bool = True  # True если диалект, False если литературная речь (ставим позже)

@dataclass
class ManualSegment:
    """сегмент из ручной разметки"""
    text: str          # текст сегмента
    is_dialect: bool   # True для диалекта, False для литературной речи в квадратных скобках

def parse_timestamp(timestamp_str: str) -> float:
    """переводим таймкод из srt в секунды

    формат: 00:00:00,031
    """
    time_part = timestamp_str.replace(',', '.')
    parts = time_part.split(':')
    hours = int(parts[0])
    minutes = int(parts[1])
    seconds = float(parts[2])
    return hours * 3600 + minutes * 60 + seconds

def parse_whisper_srt(srt_text: str) -> List[WhisperSegment]:
    """парсим whisper srt формат в сегменты

    пример блока в srt:
    1
    00:00:00,031 --> 00:00:05,739
    [SPEAKER_01]: Текст здесь
    """
    segments = []

    # разбиваем на блоки по двойным переносам строк
    blocks = re.split(r'\n\n+', srt_text.strip())

    for block in blocks:
        lines = block.strip().split('\n')
        if len(lines) < 3:
            continue

        # парсим строку с таймкодами
        timestamp_match = re.search(r'(\d{2}:\d{2}:\d{2},\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2},\d{3})', lines[1])
        if not timestamp_match:
            continue

        start_time = parse_timestamp(timestamp_match.group(1))
        end_time = parse_timestamp(timestamp_match.group(2))

        # парсим спикера и текст
        text_line = lines[2]
        speaker_match = re.match(r'\[SPEAKER_(\d+)\]:\s*(.+)', text_line)

        if speaker_match:
            speaker = f"SPEAKER_{speaker_match.group(1)}"
            text = speaker_match.group(2).strip()
        else:
            speaker = "UNKNOWN"
            text = text_line.strip()

        segments.append(WhisperSegment(
            start_time=start_time,
            end_time=end_time,
            speaker=speaker,
            text=text
        ))

    return segments

# тестируем парсер на примере
test_srt = """1
00:00:00,031 --> 00:00:05,739
[SPEAKER_01]: Ну а вот как-то искали предпотерянные вещи раньше

2
00:00:05,759 --> 00:00:16,675
[SPEAKER_00]: А, ну это самое, тут вот, я не знаю"""

parsed = parse_whisper_srt(test_srt)
print(f"распарсили {len(parsed)} сегментов")
for seg in parsed:
    print(f"{seg.speaker}: {seg.text}")

def parse_manual_annotation(text: str) -> List[ManualSegment]:
    """парсим ручную разметку с [литературной речью в скобках] и диалектным текстом

    пример:
    [Как искали раньше потерянные вещи?] А, ну э\\то са\\мое… Тут вот…

    возвращает сегменты которые чередуются между литературной (в скобках) и диалектной речью
    """
    segments = []

    # разбиваем по квадратным скобкам и отслеживаем что внутри и снаружи
    parts = re.split(r'(\[.*?\])', text)

    for part in parts:
        part = part.strip()
        if not part:
            continue

        if part.startswith('[') and part.endswith(']'):
            # литературная речь (интервьюер)
            content = part[1:-1].strip()
            # пропускаем технические комментарии типа [...] или [Соб. ...]
            if content and not content.startswith('…') and not content.startswith('Соб.'):
                segments.append(ManualSegment(text=content, is_dialect=False))
        else:
            # диалектная речь
            if part:
                segments.append(ManualSegment(text=part, is_dialect=True))

    return segments

# тестируем парсер
test_manual = "[Как искали раньше потерянные вещи?] А, ну э\\то са\\мое… Тут вот… [А к столу привязывали что-то?] А_, не_т."
parsed_manual = parse_manual_annotation(test_manual)
print(f"распарсили {len(parsed_manual)} сегментов из ручной разметки")
for seg in parsed_manual:
    print(f"{'ДИАЛЕКТ' if seg.is_dialect else 'ЛИТЕР.'}: {seg.text}")

"""## 3. нормализация и чистка текстов"""

def normalize_text(text: str, remove_stress_marks: bool = True) -> str:
    """нормализуем текст для сравнения сегментов

    что делаем:
    - убираем знаки ударения (бэкслеши, акценты)
    - переводим в lowercase
    - нормализуем пробелы
    - убираем пунктуацию для лучшего матчинга
    """
    # убираем знаки ударения которые часто встречаются в диалектной транскрипции
    if remove_stress_marks:
        text = re.sub(r'\\', '', text)  # убираем бэкслеши
        text = re.sub(r'[́̀̂̃̄]', '', text)  # убираем акценты

    # в lowercase
    text = text.lower()

    # нормализуем диалектные маркеры
    text = text.replace('_', '')

    # нормализуем пунктуацию и пробелы
    text = re.sub(r'[.,!?;:—–-]+', ' ', text)
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

def clean_text_for_alignment(text: str) -> str:
    """чистим текст для выравнивания (менее агрессивно чем нормализация)

    оставляем часть пунктуации но убираем знаки ударения
    используется только для самого процесса выравнивания через алайнер
    """
    # убираем знаки ударения
    text = re.sub(r'\\', '', text)
    text = re.sub(r'[́̀̂̃̄]', '', text)
    text = text.replace('_', '')

    # нормализуем пробелы
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

# тестируем нормализацию
test_dialect = "А, ну э\\то са\\мое… Тут вот… Я не зна\\ю, то\\чно и\\ли нет"
print("оригинал:", test_dialect)
print("нормализовано:", normalize_text(test_dialect))
print("почищено:", clean_text_for_alignment(test_dialect))

"""## 4. поиск и удаление литературной речи"""

def calculate_similarity_ratio(text1: str, text2: str) -> float:
    """считаем похожесть двух текстов через расстояние левенштейна

    возвращает число от 0 (совсем разные) до 1 (одинаковые)
    """
    norm1 = normalize_text(text1)
    norm2 = normalize_text(text2)

    if not norm1 or not norm2:
        return 0.0

    lev_dist = lev_distance(norm1, norm2)
    max_len = max(len(norm1), len(norm2))

    if max_len == 0:
        return 1.0

    return 1.0 - (lev_dist / max_len)

def find_matching_whisper_segments(
    standard_segments: List[ManualSegment],
    whisper_segments: List[WhisperSegment],
    threshold: float = 0.7
) -> List[int]:
    """находим сегменты whisper которые матчатся с литературной речью из ручной разметки

    что делаем:
    - берем сегменты литературной речи из ручной разметки (то что в квадратных скобках)
    - для каждого ищем самый похожий сегмент в whisper через левенштейн
    - если похожесть выше порога - помечаем этот сегмент whisper как литературный

    аргументы:
        standard_segments: список литературных сегментов из ручной разметки
        whisper_segments: все сегменты из whisper
        threshold: порог похожести (0-1) для матчинга, дефолт 0.7

    возвращает:
        список индексов whisper сегментов которые надо пометить как литературные
    """
    standard_indices = []

    for standard_seg in standard_segments:
        if not standard_seg.is_dialect:  # только для литературной речи
            best_match_idx = -1
            best_similarity = 0.0

            # ищем самый похожий сегмент в whisper
            for i, whisper_seg in enumerate(whisper_segments):
                similarity = calculate_similarity_ratio(standard_seg.text, whisper_seg.text)

                if similarity > best_similarity:
                    best_similarity = similarity
                    best_match_idx = i

            # если нашли достаточно похожий и еще не использовали этот индекс
            if best_similarity >= threshold and best_match_idx not in standard_indices:
                standard_indices.append(best_match_idx)
                print(f"нашли матч (похожесть={best_similarity:.2f}):")
                print(f"  ручная разметка: {standard_seg.text[:60]}")
                print(f"  whisper: {whisper_segments[best_match_idx].text[:60]}")

    return standard_indices

# тестируем расчет похожести
text1 = "Как искали раньше потерянные вещи"
text2 = "Ну а вот как-то искали предпотерянные вещи раньше"
print(f"похожесть: {calculate_similarity_ratio(text1, text2):.2f}")

"""## 5. кастомная сегментация для lingtrain aligner"""

def segment_text_with_pauses(text: str, pause_marker: str = '…') -> List[str]:
    """сегментируем текст с учетом маркеров пауз (…) которые показывают естественные разрывы

    это важно потому что:
    - в ручной разметке используют … для пауз
    - в whisper могут быть полные предложения без пауз
    - нам надо чтобы сегментация была более-менее похожей

    стратегия:
    1. сначала разбиваем по маркерам пауз (…) и знакам препинания
    2. потом разбиваем каждую часть по границам предложений если слишком длинная
    3. склеиваем очень короткие сегменты
    """
    # сначала разбиваем по маркерам пауз и сильной пунктуации
    parts = re.split(r'[.!?]+', text)

    segments = []
    current_segment = ""

    for part in parts:
        part = part.strip()
        if not part:
            continue

        # если текущий сегмент пустой - начинаем новый
        if not current_segment:
            current_segment = part
        # если добавление этой части сделает сегмент слишком длинным - сохраняем текущий и начинаем новый
        elif len(current_segment.split()) + len(part.split()) > 30:
            segments.append(current_segment)
            current_segment = part
        # если текущий сегмент очень короткий - склеиваем
        elif len(current_segment.split()) < 5:
            current_segment += " " + part
        # иначе сохраняем текущий и начинаем новый
        else:
            segments.append(current_segment)
            current_segment = part

    # добавляем последний сегмент
    if current_segment:
        segments.append(current_segment)

    return [s.strip() for s in segments if s.strip()]

def prepare_text_for_alignment(segments: List[str], join_short: bool = True) -> List[Tuple[str, str]]:
    """готовим сегментированный текст для выравнивания

    ВАЖНО: теперь возвращаем пары (оригинал, почищенный_для_алайнера)
    это нужно чтобы потом смапить выравненные пары обратно на оригинальные тексты со слэшами

    что делаем:
    - сохраняем оригинальный сегмент как есть
    - делаем почищенную версию (убираем знаки ударения и тд) для самого выравнивания
    - опционально склеиваем очень короткие сегменты (меньше 3 слов) со следующим

    аргументы:
        segments: список текстовых сегментов (оригинальных)
        join_short: склеивать ли очень короткие сегменты, дефолт True

    возвращает:
        список пар (оригинальный_текст, почищенный_текст)
    """
    # создаем пары оригинал-почищенный
    pairs = [(seg, clean_text_for_alignment(seg)) for seg in segments]

    # фильтруем пустые
    pairs = [(orig, clean) for orig, clean in pairs if clean]

    if not join_short:
        return pairs

    # склеиваем очень короткие сегменты (< 3 слов) со следующим
    result = []
    i = 0
    while i < len(pairs):
        orig_current, clean_current = pairs[i]

        # если этот сегмент короткий и есть следующий - склеиваем
        if len(clean_current.split()) < 3 and i + 1 < len(pairs):
            orig_next, clean_next = pairs[i + 1]
            orig_current = orig_current + " " + orig_next
            clean_current = clean_current + " " + clean_next
            i += 2
        else:
            i += 1

        result.append((orig_current, clean_current))

    return result

# тестируем сегментацию
test_text = "А, ну это самое… Тут вот… Я не знаю, точно или нет. Но была в Берегу женщина."
segments = segment_text_with_pauses(test_text)
print(f"разбили на {len(segments)} частей:")
for i, seg in enumerate(segments, 1):
    print(f"{i}. {seg}")

"""## 6. основные функции пайплайна"""

def extract_dialect_text(
    whisper_srt: str,
    manual_text: str,
    similarity_threshold: float = 0.65
) -> Tuple[str, str, Dict]:
    """вытаскиваем только диалектную речь из whisper и ручной разметки

    что делаем:
    - парсим оба источника
    - находим литературную речь в ручной разметке (в квадратных скобках)
    - матчим ее с сегментами whisper через левенштейн
    - помечаем найденные сегменты как литературные
    - собираем только диалектные сегменты в один текст

    аргументы:
        whisper_srt: текст srt файла из whisper
        manual_text: текст ручной разметки
        similarity_threshold: порог для матчинга литературной речи, дефолт 0.65

    возвращает:
        кортеж из (текст_диалекта_whisper, текст_диалекта_ручной, статистика)
    """
    print("=" * 60)
    print("вытаскиваем диалектную речь")
    print("=" * 60)

    # парсим входные данные
    whisper_segments = parse_whisper_srt(whisper_srt)
    manual_segments = parse_manual_annotation(manual_text)

    print(f"\nраспарсили {len(whisper_segments)} сегментов whisper")
    print(f"распарсили {len(manual_segments)} сегментов ручной разметки")

    # вытаскиваем литературную речь из ручной разметки
    standard_segments = [s for s in manual_segments if not s.is_dialect]
    print(f"\nнашли {len(standard_segments)} сегментов литературной речи в ручной разметке")

    # ищем соответствующие сегменты в whisper
    print("\nматчим литературную речь в whisper...")
    standard_indices = find_matching_whisper_segments(
        standard_segments,
        whisper_segments,
        threshold=similarity_threshold
    )

    print(f"\nпометили {len(standard_indices)} сегментов whisper как литературную речь")

    # помечаем сегменты whisper
    for idx in standard_indices:
        whisper_segments[idx].is_dialect = False

    # вытаскиваем диалектные сегменты
    whisper_dialect = [s.text for s in whisper_segments if s.is_dialect]
    manual_dialect = [s.text for s in manual_segments if s.is_dialect]

    # склеиваем в непрерывный текст
    whisper_dialect_text = " ".join(whisper_dialect)
    manual_dialect_text = " ".join(manual_dialect)

    stats = {
        'whisper_total': len(whisper_segments),
        'whisper_dialect': len(whisper_dialect),
        'whisper_standard': len(standard_indices),
        'manual_total': len(manual_segments),
        'manual_dialect': len(manual_dialect),
        'manual_standard': len(standard_segments)
    }

    print("\n" + "=" * 60)
    print("результаты извлечения")
    print("=" * 60)
    print(f"whisper: {stats['whisper_dialect']}/{stats['whisper_total']} диалектных сегментов")
    print(f"ручная разметка: {stats['manual_dialect']}/{stats['manual_total']} диалектных сегментов")
    print(f"\nдлина текста диалекта whisper: {len(whisper_dialect_text)} символов")
    print(f"длина текста диалекта ручной разметки: {len(manual_dialect_text)} символов")

    return whisper_dialect_text, manual_dialect_text, stats

"""## 7. выравнивание через lingtrain с labse"""

def align_dialect_texts(
    whisper_text: str,
    manual_text: str,
    output_dir: str,
    model_name: str = 'sentence-transformers/LaBSE',
    similarity_threshold: float = 0.5,
    window_size: int = 5
) -> Tuple[List[Tuple[str, str]], Dict]:
    """выравниваем диалектные тексты через lingtrain aligner с labse

    это главная функция которая делает всё выравнивание:
    1. загружает модель labse
    2. сегментирует тексты с учетом пауз
    3. создает пары (оригинал, почищенный) для каждого сегмента
    4. выравнивает почищенные версии через алайнер
    5. решает конфликты
    6. фильтрует по длине и похожести
    7. мапит результаты обратно на оригинальные тексты СО ЗНАКАМИ УДАРЕНИЯ
    8. сохраняет результаты и визуализацию

    аргументы:
        whisper_text: текст диалекта из whisper
        manual_text: текст диалекта из ручной разметки
        output_dir: папка для результатов
        model_name: название модели sentence transformer, дефолт labse
        similarity_threshold: минимальная похожесть для пар, дефолт 0.5
        window_size: размер окна для выравнивания, дефолт 5

    возвращает:
        кортеж из (список_выравненных_пар_с_оригиналами, статистика)
    """
    print("\n" + "=" * 60)
    print("выравниваем диалектные тексты")
    print("=" * 60)

    os.makedirs(output_dir, exist_ok=True)

    # грузим модель
    print(f"\nзагружаем модель: {model_name}")
    model = SentenceTransformer(model_name)

    # сегментируем тексты с учетом пауз
    print("\nсегментируем тексты...")
    whisper_segments = segment_text_with_pauses(whisper_text)
    manual_segments = segment_text_with_pauses(manual_text)

    # готовим для выравнивания - получаем пары (оригинал, почищенный)
    whisper_pairs = prepare_text_for_alignment(whisper_segments)
    manual_pairs = prepare_text_for_alignment(manual_segments)

    print(f"whisper: {len(whisper_pairs)} сегментов")
    print(f"ручная разметка: {len(manual_pairs)} сегментов")

    # разделяем оригиналы и почищенные версии
    whisper_originals = [orig for orig, clean in whisper_pairs]
    whisper_cleaned = [clean for orig, clean in whisper_pairs]
    manual_originals = [orig for orig, clean in manual_pairs]
    manual_cleaned = [clean for orig, clean in manual_pairs]

    # создаем базу данных для алайнера
    db_path = os.path.join(output_dir, 'alignment.db')
    if os.path.exists(db_path):
        os.unlink(db_path)

    # заполняем базу ПОЧИЩЕННЫМИ версиями (для выравнивания)
    print("\nзаполняем базу данных...")
    aligner.fill_db(
        db_path,
        'whisper', 'manual',
        whisper_cleaned,
        manual_cleaned
    )

    # делаем выравнивание
    print("\nделаем выравнивание...")
    aligner.align_db(
        db_path,
        model_name=model_name,
        model=model,
        batch_size=200,
        window=window_size,
        embed_batch_size=50,
        normalize_embeddings=True,
        show_progress_bar=True,
        shift=0
    )

    # разрешаем конфликты итеративно
    print("\nразрешаем конфликты...")
    for step in range(3):
        conflicts, rest = resolver.get_all_conflicts(
            db_path,
            min_chain_length=2 + step,
            max_conflicts_len=6 * (step + 1),
            handle_start=True,
            handle_finish=True
        )
        if conflicts:
            print(f"  шаг {step+1}: разрешаем {len(conflicts)} конфликтов")
            resolver.resolve_all_conflicts(db_path, conflicts, model_name, model=model)
        if len(rest) == 0:
            break

    # финальное разрешение конфликтов
    conflicts, _ = resolver.get_all_conflicts(
        db_path,
        min_chain_length=2,
        max_conflicts_len=30,
        handle_start=True,
        handle_finish=True
    )
    if conflicts:
        print(f"  финал: разрешаем {len(conflicts)} конфликтов")
        resolver.resolve_all_conflicts(db_path, conflicts, model_name, model=model)

    # получаем выравненные пары (это почищенные версии)
    print("\nполучаем выравненные пары...")
    lines_whisper_clean, lines_manual_clean = helper.read_processing(db_path)

    if len(lines_whisper_clean) == 0:
        print("внимание: не нашли выравненных пар!")
        return [], {}

    print(f"начальных пар: {len(lines_whisper_clean)}")

    # фильтруем по соотношению длин
    MAX_LEN_RATIO = 2.0
    length_filtered = []

    for w, m in zip(lines_whisper_clean, lines_manual_clean):
        len_w = len(w.strip().split())
        len_m = len(m.strip().split())

        if len_w == 0 or len_m == 0:
            continue

        ratio = max(len_w / len_m, len_m / len_w)
        if ratio <= MAX_LEN_RATIO:
            length_filtered.append((w, m))

    print(f"после фильтра по длине: {len(length_filtered)}")

    if not length_filtered:
        print("внимание: ни одна пара не прошла фильтр по длине!")
        return [], {}

    # фильтруем по похожести
    print("\nсчитаем похожести...")
    whisper_vecs = model.encode([p[0] for p in length_filtered], show_progress_bar=False)
    manual_vecs = model.encode([p[1] for p in length_filtered], show_progress_bar=False)

    similarities = [1 - cosine(w, m) if np.any(w) and np.any(m) else 0
                   for w, m in zip(whisper_vecs, manual_vecs)]

    final_pairs_cleaned = [(w, m, sim) for (w, m), sim in zip(length_filtered, similarities)
                           if sim >= similarity_threshold]

    print(f"после фильтра по похожести (>={similarity_threshold}): {len(final_pairs_cleaned)}")

    if final_pairs_cleaned:
        avg_sim = np.mean([p[2] for p in final_pairs_cleaned])
        print(f"средняя похожесть: {avg_sim:.3f}")

    # ВАЖНО: теперь мапим обратно на оригинальные тексты со знаками ударения!
    print("\nмапим выравненные пары на оригинальные тексты со знаками ударения...")
    final_pairs_original = []

    for whisper_clean, manual_clean, sim in final_pairs_cleaned:
        # ищем оригиналы по почищенным версиям
        whisper_orig = None
        manual_orig = None

        # находим оригинальный текст whisper
        for orig, clean in whisper_pairs:
            if clean == whisper_clean:
                whisper_orig = orig
                break

        # находим оригинальный текст ручной разметки
        for orig, clean in manual_pairs:
            if clean == manual_clean:
                manual_orig = orig
                break

        # если нашли оба оригинала - добавляем
        if whisper_orig and manual_orig:
            final_pairs_original.append((whisper_orig, manual_orig, sim))

    print(f"смапили {len(final_pairs_original)} пар на оригиналы")

    # считаем chain score
    chain_score = metrics.chain_score(db_path)
    print(f"chain score: {chain_score:.3f}")

    # визуализация выравнивания
    print("\nгенерируем визуализацию...")
    vis_path = os.path.join(output_dir, 'alignment_visualization.png')
    vis_helper.visualize_alignment_by_db(
        db_path,
        output_path=vis_path,
        batch_size=500,
        size=(900, 900),
        lang_name_from='whisper',
        lang_name_to='ручная разметка',
        plt_show=False
    )
    print(f"визуализация сохранена: {vis_path}")

    # сохраняем выравненные пары с ОРИГИНАЛЬНЫМИ текстами
    output_path = os.path.join(output_dir, 'aligned_pairs_original.txt')
    with open(output_path, 'w', encoding='utf-8') as f:
        for i, (w_orig, m_orig, sim) in enumerate(final_pairs_original, 1):
            f.write(f"{i}> {w_orig}\n")
            f.write(f"{i}= {m_orig}\n")
            f.write(f"{i}# похожесть: {sim:.3f}\n\n")

    print(f"\nвыравненные пары (с оригинальной разметкой) сохранены: {output_path}")

    # также сохраняем почищенные версии для проверки
    output_path_clean = os.path.join(output_dir, 'aligned_pairs_cleaned.txt')
    with open(output_path_clean, 'w', encoding='utf-8') as f:
        for i, (w_clean, m_clean, sim) in enumerate(final_pairs_cleaned, 1):
            f.write(f"{i}> {w_clean}\n")
            f.write(f"{i}= {m_clean}\n")
            f.write(f"{i}# похожесть: {sim:.3f}\n\n")

    print(f"выравненные пары (почищенные) сохранены: {output_path_clean}")

    stats = {
        'initial_pairs': len(lines_whisper_clean),
        'length_filtered': len(length_filtered),
        'final_pairs': len(final_pairs_original),
        'avg_similarity': np.mean([p[2] for p in final_pairs_original]) if final_pairs_original else 0,
        'chain_score': chain_score
    }

    return [(w, m) for w, m, _ in final_pairs_original], stats

"""## 8. обработка csv файла"""

def process_csv_file(
    csv_path: str,
    output_base_dir: str,
    similarity_threshold: float = 0.5,
    standard_speech_threshold: float = 0.65
):
    """обрабатываем весь csv файл с несколькими записями

    что делаем:
    - читаем csv
    - для каждой строки (каждой записи):
      1. вытаскиваем диалектную речь
      2. выравниваем
      3. сохраняем результаты в отдельную папку
    - собираем общую статистику

    аргументы:
        csv_path: путь к csv файлу
        output_base_dir: базовая папка для результатов
        similarity_threshold: порог похожести для выравнивания, дефолт 0.5
        standard_speech_threshold: порог для поиска литературной речи, дефолт 0.65
    """
    print("\n" + "#" * 60)
    print("обрабатываем csv файл")
    print("#" * 60)

    # читаем csv
    df = pd.read_csv(csv_path)
    print(f"\nзагрузили {len(df)} строк из csv")

    os.makedirs(output_base_dir, exist_ok=True)

    all_results = []

    for idx, row in df.iterrows():
        print("\n" + "#" * 60)
        print(f"обрабатываем строку {idx + 1}/{len(df)}")
        print("#" * 60)

        srt_filename = row['srt_file_names']
        whisper_srt = row['orig_whisper']
        manual_text = row['orig_transcript']

        print(f"файл: {srt_filename}")

        # создаем папку для этого файла
        file_output_dir = os.path.join(output_base_dir, f"row_{idx}_{srt_filename.replace('.srt', '')}")
        os.makedirs(file_output_dir, exist_ok=True)

        try:
            # вытаскиваем диалектную речь
            whisper_dialect, manual_dialect, extract_stats = extract_dialect_text(
                whisper_srt,
                manual_text,
                similarity_threshold=standard_speech_threshold
            )

            # сохраняем вытащенные диалектные тексты
            with open(os.path.join(file_output_dir, 'whisper_dialect.txt'), 'w', encoding='utf-8') as f:
                f.write(whisper_dialect)
            with open(os.path.join(file_output_dir, 'manual_dialect.txt'), 'w', encoding='utf-8') as f:
                f.write(manual_dialect)

            # выравниваем тексты
            aligned_pairs, align_stats = align_dialect_texts(
                whisper_dialect,
                manual_dialect,
                file_output_dir,
                similarity_threshold=similarity_threshold
            )

            result = {
                'row_idx': idx,
                'filename': srt_filename,
                'output_dir': file_output_dir,
                'success': len(aligned_pairs) > 0,
                'num_pairs': len(aligned_pairs),
                **extract_stats,
                **align_stats
            }

            all_results.append(result)

            print("\n" + "=" * 60)
            print("строка обработана")
            print("=" * 60)
            print(f"выравненных пар: {len(aligned_pairs)}")

        except Exception as e:
            print(f"\nошибка при обработке строки {idx}: {e}")
            import traceback
            traceback.print_exc()

            result = {
                'row_idx': idx,
                'filename': srt_filename,
                'output_dir': file_output_dir,
                'success': False,
                'error': str(e)
            }
            all_results.append(result)

    # сохраняем сводку
    summary_df = pd.DataFrame(all_results)
    summary_path = os.path.join(output_base_dir, 'processing_summary.csv')
    summary_df.to_csv(summary_path, index=False)

    print("\n" + "#" * 60)
    print("обработка завершена")
    print("#" * 60)
    print(f"\nвсего строк обработано: {len(all_results)}")
    print(f"успешно: {sum(r['success'] for r in all_results)}")
    print(f"с ошибками: {sum(not r['success'] for r in all_results)}")
    print(f"\nсводка сохранена: {summary_path}")

    return summary_df

"""## 9. запускаем пайплайн"""

# настройки
CSV_PATH = 'pez_048.csv'
OUTPUT_DIR = 'dialect_alignment_output'
SIMILARITY_THRESHOLD = 0.6  # для финальных выравненных пар
STANDARD_SPEECH_THRESHOLD = 0.6  # для поиска литературной речи

# запускаем обработку csv файла
summary = process_csv_file(
    CSV_PATH,
    OUTPUT_DIR,
    similarity_threshold=SIMILARITY_THRESHOLD,
    standard_speech_threshold=STANDARD_SPEECH_THRESHOLD
)